name: SBOM

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  actions: read
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - name: Generate SPDX software bill of materials
        uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
        with:
          path: .
          format: spdx-json
          artifact-name: project-black-monolith.spdx.json
